### ISSUE TITLE
Resource usage (CPU, mem)

### ISSUE THREAD

**Issue by pedrolcn** [ronomon/crypto-async#14]
Hi.

I have an use case where I'll be hashing small buffers (median should be around 150 bytes, certainly smaller than 512B) on an HTTP endpoint handler where high load is expected. Right now I'm using Node's built-in crypto module and the hashing latency is so far not a problem, but on load testing it was noticed that this hashing generates high CPU usage on the server.

From what I gather from the documentations, this lib focuses mostly on providing higher latency/throughput on crypto operations, but it also mentions having less overhead on calling from JS to C, which leads me to ask, can I also expect crypto-async to have lower CPU usage when compared to built-in crypto?

Thanks in advance

**Comment by jorangreef** [comment]
Hey @pedrolcn!

For small buffers around 150 bytes, you'll pay a relatively large context switch cost to dip into the threadpool using `@ronomon/crypto-async`'s async `hash()`, so I wouldn't recommend that, and it's also not necessary because small buffers won't block your event loop.

However, if you use `@ronomon/crypto-async`'s sync `hash()`, you should notice an almost 2x decrease in latency compared to Node's synchronous crypto methods. The reason is that we do only 1 call per hash into C, compared to Node, which IIRC does at least 3 calls (init, update, digest). For small buffers, the overhead of these calls into C are almost more costly than the hash algorithm itself.

From the README, here's our benchmark result for 256 byte buffers:

```
             sha256: 16384 x 256 Bytes
               node: Latency: 0.007ms Throughput: 36.79 MB/s
      sync @ronomon: Latency: 0.002ms Throughput: 101.47 MB/s
     async @ronomon: Latency: 0.042ms Throughput: 24.05 MB/s
```

So yes, to answer your question, you should expect these sync methods to have significantly less CPU usage. Don't take my word for it, try it out and see how it goes. I'd be interested to hear back from you on what you find.

**Comment by pedrolcn** [comment]
> So yes, to answer your question, you should expect these sync methods to have significantly less CPU usage. Don't take my word for it, try it out and see how it goes. I'd be interested to hear back from you on what you find.

Interesting, does lower latency directly imply lower CPU usage ? The issue is not so much with throughput or latency, most of the request latency is due to data-fetching, hashing is a very low fraction of it, throughput is also not much of a worry, we're expecting peak loads of no more than 100 RPS, at 150bytes hashed per request this means ~15KB/s. But we're using small nodes on this server (1vCPU) so even a moderate load (~10rps) hits upwards of 80% CPU usage and triggers auto-scaling.

Thanks for your answer. I'll definitely try it out and report results

**Comment by jorangreef** [comment]
> Interesting, does lower latency directly imply lower CPU usage ?

Not necessarily, but in this case yes. It's all going into function calling, argument passing, converting V8 types to C types, return values etc. all CPU work, plus the JavaScript object instantiation and GC for creating a crypto hash stream to wrap all of that.
