### ISSUE TITLE
Enable CBC

### ISSUE THREAD

**Issue by eduardhasanaj** [ronomon/crypto-async#8]
Hi,
Is there any possibility to decrypt text that was  decrypted with AES/CBC/PKCS5Padding?
Your package is the only possibility that we have but CBC is not supported.
In fact it says algorithm disabled.
Best regards

**Comment by jorangreef** [comment]
Thanks @eduardhasanaj2 

Cloudflare have a fantastic write-up of the major cryptographic weaknesses in CBC:

https://blog.cloudflare.com/padding-oracles-and-the-decline-of-cbc-mode-ciphersuites/

From our point of view, the OpenSSL interface for CBC is also more complicated and dangerous.

For both these reasons, we have disabled CBC explicitly because it's not secure, as a feature of crypto-async not a shortcoming. I would recommend that instead of adding support for CBC, you rather switch to a better, faster, secure algorithm in your application.

I hope this answer will encourage you and get you excited enough to want better than CBC.
